# -*- coding: utf-8 -*-
"""custom_encoder_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdN34DlaU8k8JG0aNdKnTFJq4blyb7Zk

# Custom Speech Encoder v2
**Architecture**: Conv stem → 6-layer Transformer with sinusoidal PE

**Training objectives (3 losses):**
- MSE reconstruction loss (0.4) — captures acoustic detail, speaker identity, prosody
- CTC loss on characters (0.4) — forces phoneme/linguistic structure in the latent
- InfoNCE contrastive loss (0.2) — makes the latent space robust via augmentation

**Output**: `(B, T, 768)` — drop-in replacement for your existing ModalityAdapter input

## 1. Install dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install torch torchaudio transformers datasets librosa soundfile \
#              pandas numpy tqdm tensorboard torchinfo

"""## 2. Config — all hyperparameters in one place"""

import torch

# ── Audio ──────────────────────────────────────────────────────────────────
MEL_SR       = 22050
N_MELS       = 80
N_FFT        = 1024
HOP_LENGTH   = 256
WIN_LENGTH   = 1024
FMIN         = 0.0
FMAX         = 8000.0
MAX_DURATION = 10.0          # seconds — clips longer than this are truncated
MAX_MEL_LEN  = int(MAX_DURATION * MEL_SR / HOP_LENGTH)  # ~862 frames

# ── Encoder architecture ───────────────────────────────────────────────────
HIDDEN_DIM    = 768
ENCODER_HEADS = 12
ENCODER_LAYERS= 6
FFN_DIM       = 3072          # 4 * HIDDEN_DIM
DROPOUT       = 0.1

# ── CTC head ───────────────────────────────────────────────────────────────
# LJSpeech characters + blank token
CHARS = list(" abcdefghijklmnopqrstuvwxyz',-.")
VOCAB = {c: i+1 for i, c in enumerate(CHARS)}   # 1-indexed; 0 = CTC blank
VOCAB_SIZE = len(CHARS) + 1                      # +1 for blank

# ── Training ───────────────────────────────────────────────────────────────
BATCH_SIZE   = 16
LR           = 3e-4
WARMUP_STEPS = 500
MAX_STEPS    = 20000
GRAD_ACCUM   = 2
FP16         = True
SAVE_EVERY   = 2000
LOG_EVERY    = 100

# ── Loss weights ───────────────────────────────────────────────────────────
W_RECON      = 0.4
W_CTC        = 0.4
W_CONTRAST   = 0.2
TEMP         = 0.07           # InfoNCE temperature

# ── Paths ──────────────────────────────────────────────────────────────────
DATA_ROOT    = 'LJSpeech-1.1'
TRAIN_CSV    = 'train.csv'
VAL_CSV      = 'val.csv'
OUTPUT_DIR   = '.'

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
print(f'MAX_MEL_LEN: {MAX_MEL_LEN}')
print(f'VOCAB_SIZE: {VOCAB_SIZE}')

# ── Stage A additions (add at bottom of Cell 2) ───────────────────────────
LLM_ID           = 'HuggingFaceTB/SmolLM2-1.7B'
LLM_DIM          = 2048
NUM_AUDIO_TOKENS = 32
LORA_RANK        = 16
LORA_ALPHA       = 32
LORA_DROPOUT     = 0.05
LORA_TARGETS     = ['q_proj', 'v_proj', 'o_proj']
BATCH_SIZE_A     = 8       # use separate var to not overwrite encoder BATCH_SIZE
GRAD_ACCUM_A     = 4
LR_A             = 2e-4
WARMUP_STEPS_A   = 300
MAX_STEPS_A      = 15000
SAVE_EVERY_A     = 1500
LOG_EVERY_A      = 50
MAX_TEXT_LEN     = 128
OUTPUT_DIR_A     = 'stage_a_checkpoints'

"""## 3. LJSpeech download + manifest (reuse your existing split if you have it)"""

import os, pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

# ── Download if not present ─────────────────────────────────────────────────
if not Path(DATA_ROOT).exists():
    print('Downloading LJSpeech...')
    !wget -q https://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2
    !tar -xjf LJSpeech-1.1.tar.bz2
    print('Done.')
else:
    print('LJSpeech already present.')

# ── Build / load manifest ───────────────────────────────────────────────────
if not Path(TRAIN_CSV).exists():
    df = pd.read_csv(f'{DATA_ROOT}/metadata.csv', sep='|', header=None,
                     names=['id', 'transcript', 'normalized'])
    df['wav_path'] = f'{DATA_ROOT}/wavs/' + df['id'] + '.wav'
    df['text'] = df['normalized'].str.lower().str.strip()
    df['text_len'] = df['text'].str.len()
    df = df[(df['text_len'] >= 5) & (df['text_len'] <= 190)]

    train_val, test = train_test_split(df, test_size=0.10, random_state=42)
    train, val      = train_test_split(train_val, test_size=0.111, random_state=42)

    train[['id','wav_path','text']].to_csv(TRAIN_CSV, index=False)
    val[['id','wav_path','text']].to_csv(VAL_CSV, index=False)
    print(f'train: {len(train)} | val: {len(val)}')
else:
    train = pd.read_csv(TRAIN_CSV)
    val   = pd.read_csv(VAL_CSV)
    print(f'Loaded existing splits: train={len(train)}, val={len(val)}')

"""## 4. Mel spectrogram + augmentation helpers"""

import torch
import torchaudio
import torchaudio.transforms as T

# ── Mel transform ───────────────────────────────────────────────────────────
# Instantiate MelSpectrogram on CPU to avoid CUDA multiprocessing issues in workers
mel_transform_cpu = T.MelSpectrogram(
    sample_rate=MEL_SR,
    n_fft=N_FFT,
    win_length=WIN_LENGTH,
    hop_length=HOP_LENGTH,
    n_mels=N_MELS,
    f_min=FMIN,
    f_max=FMAX,
    power=1.0,
).cpu() # Initialize on CPU


def wav_to_mel(wav: torch.Tensor, orig_sr: int) -> torch.Tensor:
    """ (C, T) → (N_MELS, T_frames) log-mel, clamped to MAX_MEL_LEN. Returns CPU tensor. """
    if orig_sr != MEL_SR:
        wav = T.Resample(orig_sr, MEL_SR)(wav)
    if wav.shape[0] > 1:
        wav = wav.mean(0, keepdim=True)
    # Ensure wav is on CPU before mel_transform_cpu
    wav = wav.cpu() # Ensure wav is on CPU for the transform
    mel = mel_transform_cpu(wav).squeeze(0)  # Use the CPU transform
    mel = torch.log(torch.clamp(mel, min=1e-5))
    # truncate or pad to MAX_MEL_LEN
    T_frames = mel.shape[1]
    if T_frames > MAX_MEL_LEN:
        mel = mel[:, :MAX_MEL_LEN]
    elif T_frames < MAX_MEL_LEN:
        pad = MAX_MEL_LEN - T_frames
        mel = torch.nn.functional.pad(mel, (0, pad), value=-11.5)  # log(1e-5)
    return mel   # (N_MELS, MAX_MEL_LEN) - explicitly a CPU tensor

"""## 5. Dataset"""

import torchaudio
from torch.utils.data import Dataset, DataLoader
import torch.multiprocessing

torch.multiprocessing.set_start_method('spawn', force=True)

class LJSpeechEncoderDataset(Dataset):
    def __init__(self, csv_path: str):
        self.df = pd.read_csv(csv_path)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        wav, sr = torchaudio.load(row['wav_path'])

        mel      = wav_to_mel(wav, sr)          # (N_MELS, MAX_MEL_LEN)
        mel_aug  = augment_mel(mel)             # augmented view for contrastive
        label_ids = text_to_ids(str(row['text']))

        return {
            'mel'      : mel,
            'mel_aug'  : mel_aug,
            'label_ids': torch.tensor(label_ids, dtype=torch.long),
            'label_len': len(label_ids),
        }


def collate_fn(batch):
    mels      = torch.stack([b['mel']     for b in batch])     # (B, N_MELS, T)
    mels_aug  = torch.stack([b['mel_aug'] for b in batch])
    label_ids = torch.nn.utils.rnn.pad_sequence(
        [b['label_ids'] for b in batch], batch_first=True, padding_value=0
    )                                                           # (B, L_max)
    label_lens = torch.tensor([b['label_len'] for b in batch], dtype=torch.long)
    return mels, mels_aug, label_ids, label_lens


train_ds = LJSpeechEncoderDataset(TRAIN_CSV)
val_ds   = LJSpeechEncoderDataset(VAL_CSV)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=2, collate_fn=collate_fn, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=2, collate_fn=collate_fn, pin_memory=True)

print(f'train: {len(train_ds)} | val: {len(val_ds)}')
# quick shape check
m, ma, li, ll = next(iter(train_loader))
print(f'mel: {m.shape}, aug: {ma.shape}, label_ids: {li.shape}, lens: {ll}')

"""## 6. Custom Encoder architecture"""

import torch
import torch.nn as nn
import math


# Sinusoidal positional encoding
class SinusoidalPE(nn.Module):
    def __init__(self, d_model: int, max_len: int = 4096):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        pos = torch.arange(0, max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer('pe', pe.unsqueeze(0))  # (1, max_len, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, T, d_model)
        return x + self.pe[:, :x.size(1)]


#  Conv stem (2× downsampling, mel_bins → hidden_dim)
class ConvStem(nn.Module):
    def __init__(self, n_mels: int, hidden_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            # layer 1: project mel bins to hidden_dim, no downsampling
            nn.Conv1d(n_mels, hidden_dim, kernel_size=3, padding=1),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),   # applied after permute below
        )
        # separate stride-2 conv for downsampling
        self.downsample = nn.Conv1d(hidden_dim, hidden_dim,
                                    kernel_size=3, stride=2, padding=1)
        self.norm1 = nn.LayerNorm(hidden_dim)
        self.norm2 = nn.LayerNorm(hidden_dim)

    def forward(self, mel: torch.Tensor) -> torch.Tensor:
        # mel: (B, N_MELS, T)
        x = self.net[0](mel)             # (B, hidden_dim, T)
        x = self.net[1](x)               # GELU
        x = self.norm1(x.permute(0,2,1)).permute(0,2,1)  # LayerNorm on channels
        x = self.downsample(x)           # (B, hidden_dim, T/2)
        x = self.norm2(x.permute(0,2,1)).permute(0,2,1)
        return x.permute(0, 2, 1)        # (B, T/2, hidden_dim)


#  The encoder (frozen after training)
class CustomSpeechEncoder(nn.Module):
    """
    Input : (B, N_MELS, T)
    Output: (B, T/2, HIDDEN_DIM)  — compatible with ModalityAdapter
    """
    def __init__(
        self,
        n_mels      : int = N_MELS,
        hidden_dim  : int = HIDDEN_DIM,
        num_layers  : int = ENCODER_LAYERS,
        nhead       : int = ENCODER_HEADS,
        ffn_dim     : int = FFN_DIM,
        dropout     : float = DROPOUT,
    ):
        super().__init__()
        self.conv_stem = ConvStem(n_mels, hidden_dim)
        self.pos_enc   = SinusoidalPE(hidden_dim)

        layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=nhead,
            dim_feedforward=ffn_dim,
            dropout=dropout,
            activation='gelu',
            batch_first=True,
            norm_first=True,   # pre-norm (more stable)
        )
        self.transformer = nn.TransformerEncoder(layer, num_layers=num_layers)
        self.out_norm    = nn.LayerNorm(hidden_dim)

    def forward(self, mel: torch.Tensor) -> torch.Tensor:
        x = self.conv_stem(mel)      # (B, T/2, hidden_dim)
        x = self.pos_enc(x)          # + sinusoidal PE
        x = self.transformer(x)      # (B, T/2, hidden_dim)
        x = self.out_norm(x)
        return x                     # (B, T/2, 768)


#  Reconstruction decoder (training only, discarded afterward)
class ReconDecoder(nn.Module):
    """
    Symmetric decoder: (B, T/2, hidden_dim) → (B, N_MELS, T)
    Used only during training for the reconstruction loss.
    """
    def __init__(self, n_mels: int = N_MELS, hidden_dim: int = HIDDEN_DIM):
        super().__init__()
        # 2× upsample via ConvTranspose1d
        self.upsample = nn.ConvTranspose1d(hidden_dim, hidden_dim,
                                           kernel_size=3, stride=2,
                                           padding=1, output_padding=1)
        self.norm     = nn.LayerNorm(hidden_dim)
        self.proj     = nn.Conv1d(hidden_dim, n_mels, kernel_size=1)

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        # z: (B, T/2, hidden_dim)  — stop gradient from decoder back to encoder
        x = z.detach().permute(0, 2, 1)          # (B, hidden_dim, T/2)
        x = self.upsample(x)                      # (B, hidden_dim, T)
        x = self.norm(x.permute(0,2,1)).permute(0,2,1)
        x = self.proj(x)                          # (B, N_MELS, T)
        return x


# CTC head (training only)
class CTCHead(nn.Module):
    def __init__(self, hidden_dim: int = HIDDEN_DIM, vocab_size: int = VOCAB_SIZE):
        super().__init__()
        self.proj = nn.Linear(hidden_dim, vocab_size)

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.proj(z)   # (B, T/2, vocab_size) — log_softmax applied in loss


#  Full training model
class SpeechEncoderTraining(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = CustomSpeechEncoder()
        self.decoder = ReconDecoder()
        self.ctc_head= CTCHead()

        self.ctc_loss  = nn.CTCLoss(blank=0, reduction='mean', zero_infinity=True)
        self.recon_loss= nn.MSELoss()

    def forward(self, mel, mel_aug, label_ids, label_lens):
        B, _, T_orig = mel.shape

        # Encode both views
        z      = self.encoder(mel)        # (B, T/2, 768)  — main view
        z_aug  = self.encoder(mel_aug)    # (B, T/2, 768)  — augmented view
        T_enc  = z.size(1)               # T/2

        # 1. Reconstruction loss (decoder uses detached z)
        mel_hat    = self.decoder(z)                         # (B, N_MELS, T)
        # decoder output may differ from T_orig by 1 frame due to stride
        min_t      = min(mel_hat.shape[-1], T_orig)
        loss_recon = self.recon_loss(mel_hat[:, :, :min_t], mel[:, :, :min_t])

        # 2. CTC loss
        log_probs   = self.ctc_head(z).log_softmax(-1)      # (B, T/2, V)
        log_probs_t = log_probs.permute(1, 0, 2)            # (T/2, B, V) — CTC wants this
        input_lens  = torch.full((B,), T_enc, dtype=torch.long, device=mel.device)
        loss_ctc    = self.ctc_loss(log_probs_t, label_ids, input_lens, label_lens)

        # 3. InfoNCE contrastive loss
        # Pool over time → (B, 768); compare z vs z_aug
        z_pool     = z.mean(dim=1)          # (B, 768)
        z_aug_pool = z_aug.mean(dim=1)      # (B, 768)

        # L2 normalise
        z_n    = nn.functional.normalize(z_pool,     dim=-1)
        z_aug_n= nn.functional.normalize(z_aug_pool, dim=-1)

        # Cosine similarity matrix (B, B)
        sim = torch.matmul(z_n, z_aug_n.T) / TEMP
        labels_c = torch.arange(B, device=mel.device)
        loss_contrast = (
            nn.functional.cross_entropy(sim, labels_c) +
            nn.functional.cross_entropy(sim.T, labels_c)
        ) / 2.0

        # Combined loss
        loss = W_RECON * loss_recon + W_CTC * loss_ctc + W_CONTRAST * loss_contrast

        return loss, {
            'total'   : loss.item(),
            'recon'   : loss_recon.item(),
            'ctc'     : loss_ctc.item(),
            'contrast': loss_contrast.item(),
        }


# Instantiate + print stats
model = SpeechEncoderTraining().to(device)

enc_params  = sum(p.numel() for p in model.encoder.parameters())  / 1e6
dec_params  = sum(p.numel() for p in model.decoder.parameters())  / 1e6
ctc_params  = sum(p.numel() for p in model.ctc_head.parameters()) / 1e6
total_train = sum(p.numel() for p in model.parameters() if p.requires_grad) / 1e6

print(f'Encoder params : {enc_params:.1f}M  ← this is what we keep')
print(f'Decoder params : {dec_params:.1f}M  (training only, discarded)')
print(f'CTC head params: {ctc_params:.1f}M  (training only, discarded)')
print(f'Total trainable: {total_train:.1f}M')

# Shape sanity check
with torch.no_grad():
    dummy_mel = torch.randn(2, N_MELS, MAX_MEL_LEN).to(device)
    z_test    = model.encoder(dummy_mel)
    print(f'\nEncoder output shape: {z_test.shape}')  # (2, ~431, 768)
    print('Expected: (2, ~431, 768) — compatible with ModalityAdapter ✓')

# CUSTOM SPEECH ENCODER — ARCHITECTURE SUMMARY

import gc
from torchinfo import summary

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("  CUSTOM SPEECH ENCODER v2 — ARCHITECTURE")

# Print full torchinfo summary
print(" Full Model Architecture:\n")
summary(
    model.encoder,
    input_data=torch.randn(1, N_MELS, MAX_MEL_LEN).to(device),
    col_names=["input_size", "output_size", "num_params", "trainable"],
    col_width=20,
    row_settings=["var_names"],
    depth=4,
    verbose=1,
)


print(" Component Breakdown:")

components = {
    "ConvStem (kept)":         model.encoder.conv_stem,
    "Positional Encoding (kept)": model.encoder.pos_enc,
    "Transformer (kept)":      model.encoder.transformer,
    "Output Norm (kept)":      model.encoder.out_norm,
    "Recon Decoder (discard)": model.decoder,
    "CTC Head (discard)":      model.ctc_head,
}

total_keep    = 0
total_discard = 0

for name, module in components.items():
    n = sum(p.numel() for p in module.parameters())
    kept = "(discard)" not in name
    tag  = "ok" if kept else "trash"
    print(f"   {tag} {name:<35} {n/1e6:>6.2f}M params")
    if kept:
        total_keep    += n
    else:
        total_discard += n

total = total_keep + total_discard
print(f"   {'Encoder (saved to .pt)':<40} {total_keep/1e6:>6.2f}M params")
print(f"   {'Training scaffolding (discarded)':<40} {total_discard/1e6:>6.2f}M params")
print(f"   {'Total (during training)':<40} {total/1e6:>6.2f}M params")
print(" Data Flow:")

print(f"   Input mel        : (B, {N_MELS}, {MAX_MEL_LEN})  ← {MAX_DURATION}s audio @ {MEL_SR}Hz")
print(f"   After ConvStem   : (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  ← 2× time downsampled")
print(f"   After Transformer: (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  ← {ENCODER_LAYERS} layers, {ENCODER_HEADS} heads")
print(f"   Encoder output   : (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  → ModalityAdapter input ✓")
print()
print("   Training branches:")
print(f"   ├── Recon Decoder → (B, {N_MELS}, {MAX_MEL_LEN})   MSE loss  (weight={W_RECON})")
print(f"   ├── CTC Head      → (B, {MAX_MEL_LEN//2}, {VOCAB_SIZE})   CTC loss  (weight={W_CTC})")
print(f"   └── InfoNCE       → scalar          Contrastive (weight={W_CONTRAST})")
print()
print(" Encoder output compatible with ModalityAdapter (hidden_dim=768)")

"""## 7. Optimizer + LR scheduler"""

import torch.optim as optim
import math

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-2,
                        betas=(0.9, 0.98), eps=1e-9)


def get_lr(step: int) -> float:
    """Linear warmup → cosine decay."""
    if step < WARMUP_STEPS:
        return step / max(1, WARMUP_STEPS)
    progress = (step - WARMUP_STEPS) / max(1, MAX_STEPS - WARMUP_STEPS)
    return max(0.05, 0.5 * (1.0 + math.cos(math.pi * progress)))


scheduler = optim.lr_scheduler.LambdaLR(optimizer, get_lr)

# Mixed precision scaler
scaler = torch.cuda.amp.GradScaler(enabled=FP16)

print('Optimizer + scheduler ready ✓')

"""## 8. Training loop"""

import os
from tqdm import tqdm
from torch.utils.tensorboard import SummaryWriter

os.makedirs(OUTPUT_DIR, exist_ok=True)
writer = SummaryWriter(log_dir=f'{OUTPUT_DIR}/tb_logs')

step          = 0
accum_step    = 0
best_val_loss = float('inf')
running       = {k: 0.0 for k in ['total','recon','ctc','contrast']}

model.train()
optimizer.zero_grad()

print(f'Starting training for {MAX_STEPS} steps...')
print(f'Effective batch size: {BATCH_SIZE * GRAD_ACCUM}')

epoch = 0
while step < MAX_STEPS:
    epoch += 1
    for batch in train_loader:
        if step >= MAX_STEPS:
            break

        mel, mel_aug, label_ids, label_lens = [
            x.to(device) for x in batch
        ]

        #  Forward + backward
        with torch.cuda.amp.autocast(enabled=FP16):
            loss, loss_dict = model(mel, mel_aug, label_ids, label_lens)
            loss = loss / GRAD_ACCUM

        scaler.scale(loss).backward()
        accum_step += 1

        # Accumulate metrics
        for k in running:
            running[k] += loss_dict[k] / GRAD_ACCUM

        # Optimizer step
        if accum_step == GRAD_ACCUM:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad()
            accum_step = 0
            step += 1

            # Logging
            if step % LOG_EVERY == 0:
                lr_now = scheduler.get_last_lr()[0] * LR
                for k, v in running.items():
                    writer.add_scalar(f'train/{k}', v / LOG_EVERY, step)
                print(f'step {step:>6}/{MAX_STEPS} | '
                      f'loss={running["total"]/LOG_EVERY:.4f} '
                      f'recon={running["recon"]/LOG_EVERY:.4f} '
                      f'ctc={running["ctc"]/LOG_EVERY:.4f} '
                      f'contrast={running["contrast"]/LOG_EVERY:.4f} '
                      f'lr={lr_now:.2e}')
                running = {k: 0.0 for k in running}

            # Validation + checkpoint
            if step % SAVE_EVERY == 0:
                model.eval()
                val_losses = {k: 0.0 for k in ['total','recon','ctc','contrast']}
                n_val = 0
                with torch.no_grad():
                    for vbatch in val_loader:
                        vm, vma, vli, vll = [x.to(device) for x in vbatch]
                        with torch.cuda.amp.autocast(enabled=FP16):
                            _, vd = model(vm, vma, vli, vll)
                        for k in val_losses:
                            val_losses[k] += vd[k]
                        n_val += 1

                for k in val_losses:
                    val_losses[k] /= n_val
                    writer.add_scalar(f'val/{k}', val_losses[k], step)

                print(f'\n>>> VAL step {step} | '
                      f'total={val_losses["total"]:.4f} '
                      f'recon={val_losses["recon"]:.4f} '
                      f'ctc={val_losses["ctc"]:.4f} '
                      f'contrast={val_losses["contrast"]:.4f}')

                # Save full checkpoint
                ckpt = {
                    'step'            : step,
                    'encoder_state'   : model.encoder.state_dict(),
                    'decoder_state'   : model.decoder.state_dict(),
                    'ctc_head_state'  : model.ctc_head.state_dict(),
                    'optimizer_state' : optimizer.state_dict(),
                    'scheduler_state' : scheduler.state_dict(),
                    'val_loss'        : val_losses['total'],
                }
                torch.save(ckpt, f'{OUTPUT_DIR}/ckpt_step{step}.pt')

                if val_losses['total'] < best_val_loss:
                    best_val_loss = val_losses['total']
                    torch.save(ckpt, f'{OUTPUT_DIR}/best.pt')
                    print(f'  ↳ New best val loss: {best_val_loss:.4f}  (saved best.pt)')

                model.train()

writer.close()
print(f'\nTraining complete. Best val loss: {best_val_loss:.4f}')

"""## 9. Export — save ONLY the encoder (everything else is discarded)"""

# Load best checkpoint
best_ckpt = torch.load(f'{OUTPUT_DIR}/best.pt', map_location=device)
model.encoder.load_state_dict(best_ckpt['encoder_state'])
model.encoder.eval()

# Save just the encoder state_dict — this replaces custom_autoencoder.pt
torch.save(
    model.encoder.state_dict(),
    f'{OUTPUT_DIR}/custom_encoder_v2.pt'
)
print(f'Encoder saved to {OUTPUT_DIR}/custom_encoder_v2.pt')
print(f'Encoder params: {sum(p.numel() for p in model.encoder.parameters())/1e6:.1f}M')

"""## 10. Inference test — verify encoder output is ModalityAdapter-compatible"""

import torch
import torch.nn as nn
import torchaudio
import pandas as pd

# MODALITY ADAPTER

class ModalityAdapter(nn.Module):
    def __init__(
        self,
        encoder_dim: int = 768,
        llm_dim: int = 2048,
        num_query_tokens: int = 32,
        num_qformer_layers: int = 2,
        nhead: int = 8,
        ffn_dim: int = 512,
    ):
        super().__init__()

        # 1. Conv downsampler
        self.conv_downsample = nn.Sequential(
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
        )

        # 2. Q-Former in encoder_dim (768)
        self.query_tokens = nn.Parameter(torch.randn(1, num_query_tokens, encoder_dim))
        qformer_layer = nn.TransformerDecoderLayer(
            d_model=encoder_dim,
            nhead=nhead,
            dim_feedforward=ffn_dim,
            batch_first=True,
            activation='gelu',
        )
        self.qformer = nn.TransformerDecoder(qformer_layer, num_layers=num_qformer_layers)
        self.norm = nn.LayerNorm(encoder_dim)

        # 3. Project up to LLM dim after Q-Former
        self.linear_proj = nn.Linear(encoder_dim, llm_dim)

    def forward(self, encoder_output: torch.Tensor) -> torch.Tensor:
        B = encoder_output.size(0)
        x = encoder_output.permute(0, 2, 1)           # (B, 768, T)
        x = self.conv_downsample(x)                    # (B, 768, T/4)
        x = x.permute(0, 2, 1)                        # (B, T/4, 768)
        queries = self.query_tokens.expand(B, -1, -1)  # (B, 32, 768)
        out = self.qformer(queries, memory=x)          # (B, 32, 768)
        out = self.norm(out)
        out = self.linear_proj(out)                    # (B, 32, 2048)
        return out


# LOAD TRAINED ENCODER
encoder = CustomSpeechEncoder().to(device)
encoder.load_state_dict(torch.load('custom_encoder_v2.pt',
                                    map_location=device))
encoder.eval()

adapter = ModalityAdapter().to(device)
adapter.eval()

# RUN A REAL CLIP END-TO-END

sample = pd.read_csv('/content/train.csv').iloc[0]
wav, sr = torchaudio.load(sample['wav_path'])
mel_input = wav_to_mel(wav, sr).unsqueeze(0).to(device)  # (1, 80, 862)

with torch.no_grad():
    z            = encoder(mel_input)     # (1, ~431, 768)
    audio_tokens = adapter(z)             # (1, 32, 2048)


print('  END-TO-END SHAPE CHECK')
print(f'  Input mel        : {mel_input.shape}')    # (1, 80, 862)
print(f'  Encoder output   : {z.shape}')            # (1, ~431, 768)
print(f'  Adapter output   : {audio_tokens.shape}') # (1, 32, 2048)
print()
print(f'  Encoder stats    : min={z.min():.3f}  max={z.max():.3f}  mean={z.mean():.3f}')
print(f'  Adapter stats    : min={audio_tokens.min():.3f}  max={audio_tokens.max():.3f}  mean={audio_tokens.mean():.3f}')
print()

assert audio_tokens.shape == (1, 32, 2048), f'Shape mismatch: {audio_tokens.shape}'
print('  Shape assertion passed - ready for LLM input')
print('='*60)

# Param counts
enc_params     = sum(p.numel() for p in encoder.parameters()) / 1e6
adapter_params = sum(p.numel() for p in adapter.parameters()) / 1e6
print(f'''
  Encoder params : {enc_params:.1f}M''')
print(f'  Adapter params : {adapter_params:.1f}M')
print(f'  Combined       : {enc_params + adapter_params:.1f}M')

# ================================================
# LEARNING SANITY CHECK
# ================================================
import torch

# Test 1: Same clip twice → outputs should be identical (deterministic)
with torch.no_grad():
    z1 = encoder(mel_input)
    z2 = encoder(mel_input)
assert torch.allclose(z1, z2), "❌ Non-deterministic output"
print("✅ Test 1 passed: deterministic output")

# Test 2: Different clips → outputs should be different
sample2 = pd.read_csv(TRAIN_CSV).iloc[100]
wav2, sr2 = torchaudio.load(sample2['wav_path'])
mel2 = wav_to_mel(wav2, sr2).unsqueeze(0).to(device)
with torch.no_grad():
    z3 = encoder(mel2)
cos_sim = torch.nn.functional.cosine_similarity(
    z1.mean(1), z3.mean(1)
).item()
print(f"✅ Test 2: cosine similarity between 2 different clips = {cos_sim:.4f}")
print(f"   (random encoder gives ~1.0, trained encoder should give < 0.95)")

# Test 3: Augmented clip → similar but not identical to original
mel_aug = augment_mel(mel_input.squeeze(0)).unsqueeze(0).to(device)
with torch.no_grad():
    z_aug = encoder(mel_aug)
cos_sim_aug = torch.nn.functional.cosine_similarity(
    z1.mean(1), z_aug.mean(1)
).item()
print(f"✅ Test 3: cosine similarity original vs augmented = {cos_sim_aug:.4f}")
print(f"   (should be HIGH ~0.85-0.99 — same speech, different masking)")

# Test 4: Load best.pt and check what val loss was achieved
best_ckpt = torch.load('/content/best.pt', map_location=device)
print(f"\n📊 Training summary:")
print(f"   Best val loss : {best_ckpt['val_loss']:.4f}")
print(f"   Reached at step: {best_ckpt['step']}")
print(f"\n   Val loss interpretation:")
print(f"   > 3.0  → model barely learned anything")
print(f"   1.5-3.0 → model learning but needs more training")
print(f"   0.8-1.5 → good — usable representations")
print(f"   < 0.8  → excellent")

# ================================================
# ENCODER INFERENCE VISUALIZATION
# ================================================
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

encoder.eval()

# Pick 3 different clips
samples = pd.read_csv(TRAIN_CSV).iloc[[0, 50, 200]]

fig = plt.figure(figsize=(18, 10))
gs = gridspec.GridSpec(3, 3, figure=fig)

for row, (_, sample) in enumerate(samples.iterrows()):
    wav, sr = torchaudio.load(sample['wav_path'])
    mel = wav_to_mel(wav, sr).unsqueeze(0).to(device)

    with torch.no_grad():
        z = encoder(mel)  # (1, T/2, 768)

    mel_np = mel.squeeze(0).cpu().numpy()       # (80, T)
    z_np   = z.squeeze(0).cpu().numpy()         # (T/2, 768)

    # Col 1: input mel
    ax1 = fig.add_subplot(gs[row, 0])
    ax1.imshow(mel_np, aspect='auto', origin='lower', cmap='magma')
    ax1.set_title(f'Input Mel — "{sample["text"][:40]}..."', fontsize=8)
    ax1.set_ylabel('Mel bins')

    # Col 2: encoder output (first 64 dims)
    ax2 = fig.add_subplot(gs[row, 1])
    ax2.imshow(z_np[:, :64].T, aspect='auto', origin='lower', cmap='viridis')
    ax2.set_title('Encoder latent (first 64 of 768 dims)', fontsize=8)
    ax2.set_ylabel('Latent dims')

    # Col 3: per-frame L2 norm (shows where speech activity is)
    ax3 = fig.add_subplot(gs[row, 2])
    norms = torch.norm(z.squeeze(0), dim=-1).cpu().numpy()
    ax3.plot(norms, color='royalblue')
    ax3.fill_between(range(len(norms)), norms, alpha=0.3, color='royalblue')
    ax3.set_title('Per-frame activation (L2 norm)', fontsize=8)
    ax3.set_ylabel('L2 norm')
    ax3.set_xlabel('Frame')

plt.suptitle('Custom Encoder v2 — Inference Check', fontsize=12, fontweight='bold')
plt.tight_layout()
plt.savefig('encoder_inference_check.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: encoder_inference_check.png')

# Add this test to confirm the issue is padding
# Run this in a new cell

encoder.eval()
sample = pd.read_csv(TRAIN_CSV).iloc[0]
wav, sr = torchaudio.load(sample['wav_path'])

# Test 1: full padded clip (what you have now)
mel_full = wav_to_mel(wav, sr).unsqueeze(0).to(device)

# Test 2: clip trimmed to actual speech only (no padding)
mel_np = mel_full.squeeze(0).cpu()
actual_frames = (mel_np.mean(0) > -10).sum().item()  # frames above silence threshold
print(f'Actual speech frames : {actual_frames}')
print(f'Total padded frames  : {mel_full.shape[-1]}')
print(f'Padding ratio        : {1 - actual_frames/mel_full.shape[-1]:.1%}')

with torch.no_grad():
    z_full = encoder(mel_full)

norms = torch.norm(z_full.squeeze(0), dim=-1).cpu()
print(f'\nNorm stats:')
print(f'  mean : {norms.mean():.3f}')
print(f'  std  : {norms.std():.3f}')   # if std < 0.5, LayerNorm is flattening everything
print(f'  min  : {norms.min():.3f}')
print(f'  max  : {norms.max():.3f}')

"""## Appendix — Interpreting training loss

| What you see | What it means |
|---|---|
| CTC loss drops quickly (first 2k steps) | Encoder learning phoneme order — good sign |
| Recon loss plateaus high (>0.5) | Decoder underpowered — that's fine, encoder still learns |
| Contrast loss → ~2.0 then drops | Normal InfoNCE behaviour, should reach ~0.5–1.0 |
| CTC stays very high (>5.0 after 5k steps) | Check label_ids mapping, may have encoding issue |
| NaN loss | Reduce LR to 1e-4, check for silent clips in dataset |

# Stage A: Freeze the encoder. Train ModalityAdapter + SmolLM2 + LoRA

##Cell 1 — Install
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install peft
# !pip install "torchao>=0.16.0"

"""##Cell 6 — Load SmolLM2 + LoRA"""

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import get_peft_model, LoraConfig, TaskType

print('Loading SmolLM2-1.7B...')
tokenizer = AutoTokenizer.from_pretrained(LLM_ID)
tokenizer.pad_token = tokenizer.eos_token

llm = AutoModelForCausalLM.from_pretrained(
    LLM_ID,
    torch_dtype=torch.float16 if FP16 else torch.float32,
    device_map='auto',
)

# Freeze base LLM weights
for p in llm.parameters():
    p.requires_grad = False

# Attach LoRA
lora_cfg = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=LORA_RANK,
    lora_alpha=LORA_ALPHA,
    lora_dropout=LORA_DROPOUT,
    target_modules=LORA_TARGETS,
    bias='none',
)
llm = get_peft_model(llm, lora_cfg)

lora_params = sum(p.numel() for p in llm.parameters() if p.requires_grad) / 1e6
print(f'LoRA trainable params : {lora_params:.1f}M')
llm.print_trainable_parameters()

"""##Cell 8 — Dataset"""

import pandas as pd
from torch.utils.data import Dataset, DataLoader

# ── CPU-only mel transform for DataLoader workers ──────────────────────────
mel_transform_cpu = T.MelSpectrogram(
    sample_rate=MEL_SR, n_fft=N_FFT, win_length=WIN_LENGTH,
    hop_length=HOP_LENGTH, n_mels=N_MELS, f_min=FMIN, f_max=FMAX,
    power=1.0,
)  # no .to(device) — stays on CPU

def wav_to_mel_cpu(wav, orig_sr):
    """CPU-only version for use inside DataLoader workers."""
    if orig_sr != MEL_SR:
        wav = T.Resample(orig_sr, MEL_SR)(wav)
    if wav.shape[0] > 1:
        wav = wav.mean(0, keepdim=True)
    mel = mel_transform_cpu(wav).squeeze(0)
    mel = torch.log(torch.clamp(mel, min=1e-5))
    T_frames = mel.shape[1]
    if T_frames > MAX_MEL_LEN:
        mel = mel[:, :MAX_MEL_LEN]
    elif T_frames < MAX_MEL_LEN:
        mel = torch.nn.functional.pad(mel, (0, MAX_MEL_LEN - T_frames), value=-11.5)
    return mel  # CPU tensor (80, MAX_MEL_LEN)


class StageADataset(Dataset):
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        wav, sr = torchaudio.load(row['wav_path'])
        mel = wav_to_mel_cpu(wav, sr)                      # CPU tensor

        tokens = tokenizer(
            str(row['text']),
            max_length=MAX_TEXT_LEN,
            truncation=True,
            padding='max_length',
            return_tensors='pt',
        )
        return mel, tokens['input_ids'].squeeze(0), tokens['attention_mask'].squeeze(0)


def collate_fn(batch):
    mels, ids, masks = zip(*batch)
    return torch.stack(mels), torch.stack(ids), torch.stack(masks)


train_ds = StageADataset(TRAIN_CSV)
val_ds   = StageADataset(VAL_CSV)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE_A, shuffle=True,
                          num_workers=4, collate_fn=collate_fn, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE_A, shuffle=False,
                          num_workers=2, collate_fn=collate_fn, pin_memory=True)

print(f'train: {len(train_ds)} | val: {len(val_ds)}')
mel_t, ids_t, mask_t = [x.to(device) for x in next(iter(train_loader))]
print(f'mel: {mel_t.shape} | ids: {ids_t.shape} | mask: {mask_t.shape}')

"""##Cell 5 — Load encoder (frozen) + adapter

"""

import torch
import torch.nn as nn

# MODALITY ADAPTER (moved from cell_inference for definition scope)
class ModalityAdapter(nn.Module):
    def __init__(
        self,
        encoder_dim: int = HIDDEN_DIM,
        llm_dim: int = LLM_DIM,
        num_query_tokens: int = NUM_AUDIO_TOKENS,
        num_qformer_layers: int = 2,
        nhead: int = 8,
        ffn_dim: int = 512,
    ):
        super().__init__()

        # 1. Conv downsampler
        self.conv_downsample = nn.Sequential(
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
        )

        # 2. Q-Former in encoder_dim (768)
        self.query_tokens = nn.Parameter(torch.randn(1, num_query_tokens, encoder_dim))
        qformer_layer = nn.TransformerDecoderLayer(
            d_model=encoder_dim,
            nhead=nhead,
            dim_feedforward=ffn_dim,
            batch_first=True,
            activation='gelu',
        )
        self.qformer = nn.TransformerDecoder(qformer_layer, num_layers=num_qformer_layers)
        self.norm = nn.LayerNorm(encoder_dim)

        # 3. Project up to LLM dim after Q-Former
        self.linear_proj = nn.Linear(encoder_dim, llm_dim)

    def forward(self, encoder_output: torch.Tensor) -> torch.Tensor:
        B = encoder_output.size(0)
        x = encoder_output.permute(0, 2, 1)           # (B, 768, T)
        x = self.conv_downsample(x)                    # (B, 768, T/4)
        x = x.permute(0, 2, 1)                        # (B, T/4, 768)
        queries = self.query_tokens.expand(B, -1, -1)  # (B, 32, 768)
        out = self.qformer(queries, memory=x)          # (B, 32, 768)
        out = self.norm(out)
        out = self.linear_proj(out)                    # (B, 32, 2048)
        return out


# ── Encoder: load weights, freeze everything ───────────────────────────────
encoder = CustomSpeechEncoder().to(device)
encoder.load_state_dict(torch.load(ENCODER_PATH, map_location=device))
encoder.eval()
for p in encoder.parameters():
    p.requires_grad = False

# ── Adapter: trainable ─────────────────────────────────────────────────────
adapter = ModalityAdapter().to(device)

enc_params     = sum(p.numel() for p in encoder.parameters()) / 1e6
adapter_params = sum(p.numel() for p in adapter.parameters() if p.requires_grad) / 1e6
print(f'Encoder params (frozen) : {enc_params:.1f}M')
print(f'Adapter params (train)  : {adapter_params:.1f}M')

"""##Cell 9 — Forward pass helper (the core of Stage A)"""

def forward_pass(mel_batch, input_ids, attention_mask):
    """
    1. Encode mel → (B, T/2, 768)
    2. Adapter  → (B, 32, 2048)  audio tokens
    3. Get LLM text embeddings → (B, L, 2048)
    4. Prepend audio tokens → (B, 32+L, 2048)
    5. Build labels: -100 for audio positions, token ids for text positions
    6. LLM forward → cross-entropy loss on text tokens only
    """
    B = mel_batch.size(0)

    # Step 1+2: audio tokens (encoder frozen, no grad needed)
    with torch.no_grad():
        z = encoder(mel_batch)                 # (B, T/2, 768)
    audio_tokens = adapter(z)                  # (B, 32, 2048)  — trainable

    # Step 3: text embeddings from LLM embedding table
    text_embeds = llm.get_input_embeddings()(input_ids)   # (B, L, 2048)

    # Step 4: concatenate [audio | text]
    inputs_embeds = torch.cat([audio_tokens, text_embeds], dim=1)  # (B, 32+L, 2048)

    # Step 5: attention mask — 1 for audio tokens, then original text mask
    audio_mask    = torch.ones(B, NUM_AUDIO_TOKENS,
                               dtype=attention_mask.dtype,
                               device=attention_mask.device)
    full_mask     = torch.cat([audio_mask, attention_mask], dim=1) # (B, 32+L)

    # Step 6: labels — -100 for audio positions (ignored in loss), text ids elsewhere
    ignore        = torch.full((B, NUM_AUDIO_TOKENS), -100,
                               dtype=input_ids.dtype,
                               device=input_ids.device)
    labels        = torch.cat([ignore, input_ids], dim=1)          # (B, 32+L)
    # Also ignore padding tokens
    labels[labels == tokenizer.pad_token_id] = -100

    outputs = llm(
        inputs_embeds=inputs_embeds,
        attention_mask=full_mask,
        labels=labels,
    )
    return outputs.loss


print('Forward pass helper defined ✓')

# Quick shape sanity check
mel_t, ids_t, mask_t = mel_t.to(device), ids_t.to(device), mask_t.to(device)
with torch.cuda.amp.autocast(enabled=FP16):
    test_loss = forward_pass(mel_t, ids_t, mask_t)
print(f'Test loss (untrained): {test_loss.item():.4f}')
print('Expected: ~5-8 for untrained LLM on text')

"""##Cell 10 — Optimizer + scheduler"""

import math
import torch.optim as optim

# Only adapter + LoRA params are trainable
trainable_params = list(adapter.parameters()) + \
                   [p for p in llm.parameters() if p.requires_grad]

optimizer = optim.AdamW(trainable_params, lr=LR_A,
                        weight_decay=1e-2, betas=(0.9, 0.98))


def get_lr(step):
    if step < WARMUP_STEPS_A:
        return step / max(1, WARMUP_STEPS_A)
    progress = (step - WARMUP_STEPS_A) / max(1, MAX_STEPS_A - WARMUP_STEPS_A)
    return max(0.05, 0.5 * (1.0 + math.cos(math.pi * progress)))


scheduler = optim.lr_scheduler.LambdaLR(optimizer, get_lr)
scaler    = torch.cuda.amp.GradScaler(enabled=FP16)

total_trainable = sum(p.numel() for p in trainable_params) / 1e6
print(f'Total trainable params : {total_trainable:.1f}M')
print('Optimizer ready ✓')

# Fix the LR scheduler — reset and resume from checkpoint
best_ckpt = torch.load(f'{OUTPUT_DIR_A}/ckpt_step1500.pt', map_location=device)
adapter.load_state_dict(best_ckpt['adapter_state'])
llm.load_state_dict(best_ckpt['lora_state'])

# Rebuild optimizer and scheduler fresh
optimizer = torch.optim.AdamW(
    trainable_params, lr=LR_A, weight_decay=1e-2, betas=(0.9, 0.98)
)

def get_lr(step):
    if step < WARMUP_STEPS_A:
        return step / max(1, WARMUP_STEPS_A)
    progress = (step - WARMUP_STEPS_A) / max(1, MAX_STEPS_A - WARMUP_STEPS_A)
    return max(0.05, 0.5 * (1.0 + math.cos(math.pi * progress)))

scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, get_lr)
scaler    = torch.cuda.amp.GradScaler(enabled=FP16)

# Fast-forward scheduler to step 1500 without triggering the bug
for _ in range(1500):
    optimizer.step()      # dummy step to satisfy scheduler
    scheduler.step()

print(f'LR after fast-forward: {scheduler.get_last_lr()[0] * LR_A:.2e}')
print('Expected: ~2e-4')

"""##Cell 11 — Training loop"""

import os
from tqdm import tqdm
from torch.utils.tensorboard import SummaryWriter

os.makedirs(OUTPUT_DIR_A, exist_ok=True) # Changed OUTPUT_DIR to OUTPUT_DIR_A
writer     = SummaryWriter(f'{OUTPUT_DIR_A}/tb_logs') # Changed OUTPUT_DIR to OUTPUT_DIR_A

step       = 1500
accum_step = 0
best_val   = 2.8582
running_loss = 0.0

adapter.train()
llm.train()
optimizer.zero_grad()

print(f'Starting Stage A — {MAX_STEPS_A} steps') # Changed MAX_STEPS to MAX_STEPS_A
print(f'Effective batch size: {BATCH_SIZE_A * GRAD_ACCUM_A}') # Changed BATCH_SIZE * GRAD_ACCUM to BATCH_SIZE_A * GRAD_ACCUM_A

while step < MAX_STEPS_A: # Changed MAX_STEPS to MAX_STEPS_A
    for batch in train_loader:
        if step >= MAX_STEPS_A: # Changed MAX_STEPS to MAX_STEPS_A
            break

        mel, ids, mask = [x.to(device) for x in batch]

        with torch.cuda.amp.autocast(enabled=FP16):
            loss = forward_pass(mel, ids, mask) / GRAD_ACCUM_A # Changed GRAD_ACCUM to GRAD_ACCUM_A

        scaler.scale(loss).backward()
        accum_step   += 1
        running_loss += loss.item()

        if accum_step == GRAD_ACCUM_A: # Changed GRAD_ACCUM to GRAD_ACCUM_A
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(trainable_params, 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad()
            accum_step = 0
            step      += 1

            if step % LOG_EVERY_A == 0: # Changed LOG_EVERY to LOG_EVERY_A
                avg = running_loss / LOG_EVERY_A # Changed LOG_EVERY to LOG_EVERY_A
                writer.add_scalar('train/loss', avg, step)
                writer.add_scalar('train/lr', scheduler.get_last_lr()[0] * LR_A, step) # Changed LR to LR_A
                print(f'step {step:>6}/{MAX_STEPS_A} | loss={avg:.4f} | ' # Changed MAX_STEPS to MAX_STEPS_A
                      f'lr={scheduler.get_last_lr()[0]*LR_A:.2e}') # Changed LR to LR_A
                running_loss = 0.0

            if step % SAVE_EVERY_A == 0: # Changed SAVE_EVERY to SAVE_EVERY_A
                adapter.eval(); llm.eval()
                val_loss = 0.0; n = 0
                with torch.no_grad():
                    for vb in val_loader:
                        vm, vi, vk = [x.to(device) for x in vb]
                        with torch.cuda.amp.autocast(enabled=FP16):
                            val_loss += forward_pass(vm, vi, vk).item()
                        n += 1
                val_loss /= n
                writer.add_scalar('val/loss', val_loss, step)
                print(f'\n>>> VAL step {step} | loss={val_loss:.4f}')

                ckpt = {
                    'step'          : step,
                    'adapter_state' : adapter.state_dict(),
                    'lora_state'    : llm.state_dict(),
                    'optimizer_state': optimizer.state_dict(),
                    'val_loss'      : val_loss,
                }
                torch.save(ckpt, f'{OUTPUT_DIR_A}/ckpt_step{step}.pt') # Changed OUTPUT_DIR to OUTPUT_DIR_A
                if val_loss < best_val:
                    best_val = val_loss
                    torch.save(ckpt, f'{OUTPUT_DIR_A}/best.pt') # Changed OUTPUT_DIR to OUTPUT_DIR_A
                    print(f'  ↳ New best: {best_val:.4f}')

                adapter.train(); llm.train()

writer.close()
print(f'\nStage A complete. Best val loss: {best_val:.4f}')

"""##Cell 12 — Interpret results"""

best = torch.load(f'{OUTPUT_DIR_A}/best.pt', map_location=device) # Changed OUTPUT_DIR to OUTPUT_DIR_A
print(f'Best val loss : {best["val_loss"]:.4f}  at step {best["step"]}')
print()
print('Loss interpretation:')
print('  > 4.0  → adapter not converging, check forward_pass shapes')
print('  2.5-4.0 → learning but needs more steps')
print('  1.5-2.5 → good alignment, ready for Stage B')
print('  < 1.5  → excellent, LLM strongly conditioned on audio')